filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
user.name=Grady Moran
user.email=gp.moran@ufl.edu
gpg.program=/.codespaces/bin/gh-gpgsign
init.defaultbranch=main
credential.helper=/.codespaces/bin/gitcredential_github.sh
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/gpmoran-16/BME3053C-Fall-2025
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
branch.main.vscode-merge-base=origin/main
remote.upstream.url=https://github.com/uf-bme/BME3053C-Fall-2025.git
remote.upstream.fetch=+refs/heads/*:refs/remotes/upstream/*
